---
  dataSource: "commits"
  prefix: ""
  includeMessages: "commits"
  ignoreCommitsWith: 
    - "readme"
    - "travis"
    - "deepsource"
    - "internal"
    - "bestpractice"
  changelogFilename: "CHANGELOG.md"
