---
  dataSource: "commits"
  prefix: ""
  includeMessages: "commits"
  ignoreCommitsWith:
    - "readme"
    - "travis"
    - "deepsource"
    - "internal"
    - "bestpractice"
    - "update version"
  changelogFilename: "CHANGELOG.md"
