language: python
python:
  - '3.6'

services:
  - docker

before_install:
  - curl -L https://github.com/grocy/grocy-docker/raw/master/Dockerfile-grocy > Dockerfile-grocy
  - docker-compose build grocy
  - docker pull grocy/grocy-docker:nginx
  - docker-compose up -d
  - curl -kX GET https://localhost

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - coverage run --source=pygrocydm setup.py test
  - set -e
  - pdoc3 --html pygrocydm

after_success:
  - coveralls
  - docker-compose down
